In [35]:
import numpy as np

In [36]:
import pandas as pd #importa o pandas

Series:

In [37]:
labels = ('a','b','c') #define os index da sere

In [38]:
minha_lista = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a':10, 'b':20, 'c':30}

In [39]:
pd.Series (data=minha_lista, index=labels) #cria uma serie

a    10
b    20
c    30
dtype: int64

In [40]:
series = pd.Series (data=minha_lista, index=labels) #atribui

In [41]:
series['b']

np.int64(20)

In [42]:
pd.Series(minha_lista, labels)

a    10
b    20
c    30
dtype: int64

In [43]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [44]:
ser1 = pd.Series([1, 2, 3, 4], index=['EUA', 'Alemanha', 'URSS', 'Japan'])

In [45]:
ser1

EUA         1
Alemanha    2
URSS        3
Japan       4
dtype: int64

In [46]:
ser2 = pd.Series([1, 2, 3, 4], index=['EUA', 'Alemanha', 'URSS', 'Japan'])

In [47]:
ser2

EUA         1
Alemanha    2
URSS        3
Japan       4
dtype: int64

In [48]:
ser1 + ser2 #soma as series

EUA         2
Alemanha    4
URSS        6
Japan       8
dtype: int64

Criação e fatiamento

In [49]:
np.random.seed(101) # fixa os num aleatorios

In [50]:
df = pd.DataFrame(np.random.randn(5, 4), index='A B C D E'.split(), columns='W X Y Z'.split()) #cria dataframe 5x4 com valores aleatorios

In [51]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [52]:
df['W'] #seleciona a coluna W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [53]:
type(df['W']) #mostra que uma coluna é uma Series

pandas.Series

In [54]:
type(df) #mostra que df é um DataFrame

pandas.DataFrame

In [55]:
df[['W', 'Z']] #seleciona mais de uma coluna

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [56]:
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [57]:
df['new'] #coluna new n existe, vai dar erro

KeyError: 'new'

In [58]:
df['new'] = df['W'] + df['X'] #cria nova colna somando W e X

In [59]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [60]:
df.drop('new', axis=1) #remove a col apenas na view, nao altera df original

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [56]:
df

          W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119  1.996388
B -0.134841  0.390528  0.166905  0.184502  0.255687
C  0.807706  0.072960  0.638787  0.329646  0.880666
D -0.497104 -0.754070 -0.943406  0.484752 -1.251174
E -0.116773  1.901755  0.238127  1.996652  1.784981

In [61]:
df.drop ('new', axis=1, inplace=True) #remove a coluna direto no df original

In [63]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [62]:
df.loc['A', 'W'] #busca valor usando nome da linha e col

np.float64(2.706849839399938)

In [63]:
df.loc['A'] #selec linha A pelo nome

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [70]:
df.loc[['A', 'B'], ['X', 'Y', 'Z']]

          X         Y         Z
A  1.693723 -1.706086 -1.159119
B  0.390528  0.166905  0.184502

In [64]:
df.iloc[1:4, 2:] #seleciona linhas e col pela posicao

          Y         Z
B -0.848077  0.605965
C  0.528813 -0.589001
D -0.933237  0.955057

Select condicional

In [80]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [82]:
df > 0 #dados maiores q 0

       W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [65]:
bol = df > 0 #cria mascara booleana

In [66]:
df [bol] #mostra apenas os val que atendem a condicao

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [67]:
df[df['W']>0] #W maior que 0

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [90]:
df[df['W'] > 0]['Y']

A   -1.706086
C    0.638787
Name: Y, dtype: float64

In [97]:
bol = df['W'] > 0
df2 = df[bol]
df2['Y'] #codigo equival. ao acima mas maior

A   -1.706086
C    0.638787
Name: Y, dtype: float64

In [104]:
df[(df['W']>0) | (df['Y']>1)] #linhas de w maior que 0 e de y maior que 1

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [111]:
df.reset_index(inplace=True) #reseta o indice no dataframe original

In [113]:
df

  index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [68]:
col = 'RS RJ SP AM SC'.split() #cria lista com estados

In [69]:
col

['RS', 'RJ', 'SP', 'AM', 'SC']

In [70]:
df['Estado'] = col #add coluna estado

In [118]:
df

  index         W         X         Y         Z Estado
0     A  0.302665  1.693723 -1.706086 -1.159119     RS
1     B -0.134841  0.390528  0.166905  0.184502     RJ
2     C  0.807706  0.072960  0.638787  0.329646     SP
3     D -0.497104 -0.754070 -0.943406  0.484752     AM
4     E -0.116773  1.901755  0.238127  1.996652     SC

In [71]:
df.set_index('Estado', inplace=True) #estado novo index

In [123]:
df

       index         W         X         Y         Z
Estado
RS         A  0.302665  1.693723 -1.706086 -1.159119
RJ         B -0.134841  0.390528  0.166905  0.184502
SP         C  0.807706  0.072960  0.638787  0.329646
AM         D -0.497104 -0.754070 -0.943406  0.484752
SC         E -0.116773  1.901755  0.238127  1.996652

Índices Multiníveis

In [72]:
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2'] #primeiro nivel
inside = [1, 2, 3, 1, 2, 3] #segundo nivel
hier_index = list(zip(outside, inside)) #junta as duas listas
hier_index = pd.MultiIndex.from_tuples(hier_index) #cria index multinivel

In [74]:
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [75]:
inside

[1, 2, 3, 1, 2, 3]

In [76]:
hier_index = list(zip(outside,inside))

In [77]:
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [78]:
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [79]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [80]:
df = pd.DataFrame(np.random.randn(6, 2), index=hier_index, columns=['A', 'B'])

In [81]:
df

             A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [82]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [83]:
df.index.names = ['Grupo', 'Numero']

In [84]:
df

                     A         B
Grupo Numero
G1    1       0.302665  1.693723
      2      -1.706086 -1.159119
      3      -0.134841  0.390528
G2    1       0.166905  0.184502
      2       0.807706  0.072960
      3       0.638787  0.329646

In [85]:
df.xs ('G1') #seleciona dados do G1

               A         B
Numero
1       0.302665  1.693723
2      -1.706086 -1.159119
3      -0.134841  0.390528

In [147]:
df.xs(1, level='Numero')

              A         B
Grupo
G1     0.681209  1.035125
G2     0.187125 -0.732845

Dados Ausentes

In [148]:
d = {'A':[1, 2, np.nan], 'B':[5, np.nan, np.nan], 'C':[1, 2, 3]} #dicionario com valores faltantes

In [149]:
d

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [150]:
df = pd.DataFrame(d)

In [151]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [86]:
df.dropna(thresh=2) #remove linhas com menos de 2 valores validos

                     A         B
Grupo Numero
G1    1       0.302665  1.693723
      2      -1.706086 -1.159119
      3      -0.134841  0.390528
G2    1       0.166905  0.184502
      2       0.807706  0.072960
      3       0.638787  0.329646

In [155]:
df #nao altera o df inicial, nao usamos inplace

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [156]:
df.fillna(value='Fill na') #substitui NA por algo

         A        B  C
0      1.0      5.0  1
1      2.0  Fill na  2
2  Fill na  Fill na  3

In [157]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [158]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [164]:
df.ffill() #a func df.fillna(method='ffill') apresentada em aula está co mwarning de depreciação

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  2.0  5.0  3

Groupby

In [87]:
data = {'Empresa':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Nome':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Venda':[200,120,340,124,243,350]} #dicionario passado pelo professor

In [88]:
df = pd.DataFrame(data)

In [89]:
df

  Empresa     Nome  Venda
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [90]:
group = df.groupby('Empresa') #agrupa os dados por empresa

In [91]:
group

In [92]:
group.sum() #soma os valores de cada gp

               Nome  Venda
Empresa
FB        CarlSarah    593
GOOG     SamCharlie    320
MSFT     AmyVanessa    464

In [95]:
group.describe() #calculos (min, dP) do grupo

        Venda
        count   mean         std    min     25%    50%     75%    max
Empresa
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [96]:
group.count() #conta os valores por gp

         Nome  Venda
Empresa
FB          2      2
GOOG        2      2
MSFT        2      2

In [97]:
group.sum()

               Nome  Venda
Empresa
FB        CarlSarah    593
GOOG     SamCharlie    320
MSFT     AmyVanessa    464

In [98]:
group = df.groupby('Nome')

In [99]:
group.sum().loc['Amy'] #mostra a soma dos dados da Amy

Empresa    MSFT
Venda       340
Name: Amy, dtype: object

Concatenar, juntas e mesclar

In [101]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [102]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])

In [103]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [104]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [105]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [106]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [107]:
pd.concat([df1,df2,df3]) #concatena as 3 dfs

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [108]:
pd.concat([df1,df2,df3],axis=1) #concatena os df ladoa lado

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [110]:
esquerda = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})

In [111]:
direita = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [112]:
esquerda

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [113]:
direita

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [114]:
pd.merge(esquerda,direita,how='inner',on='key') #mescla

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [115]:
esquerda = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})

In [116]:
direita = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [120]:
pd.merge(esquerda, direita, on=['key1', 'key2'])#mescla usando duas chaves

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [121]:
pd.merge(esquerda, direita, how='outer', on=['key1', 'key2']) #mantem os registros das duas tabelas

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [122]:
pd.merge(esquerda, direita, how='right', on=['key1', 'key2']) #mantem os registros da tabela direita

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [123]:
pd.merge(esquerda, direita, how='left', on=['key1', 'key2']) #mantem os da esquerda

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [203]:
#juntar

In [204]:
esquerda = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

direita = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [205]:
esquerda.join(direita)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [207]:
esquerda.join(direita, how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

operações

In [125]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [126]:
df['col2'].unique() #retorna valores unicos da coluna

array([444, 555, 666])

In [127]:
np.unique(df['col2'])

array([444, 555, 666])

In [128]:
len(np.unique(df['col2']))

3

In [129]:
df['col2'].nunique() #conta quantos unicos existem

3

In [130]:
df['col2'].value_counts() #conta a freq. de cada valor

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [235]:
df[(df['col1']>2) & (df['col2'] == 444)]

   col1  col2 col3
3     4   444  xyz

In [132]:
def vezes2(x): # faz * 2
    return x*2

In [237]:
df.sum()

col1              10
col2            2109
col3    abcdefghixyz
dtype: object

In [133]:
df['col1'].apply(vezes2) #função na ccoluna

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [134]:
df['col1'].apply(lambda x : x*x)#usa lamba pra elevar ao quadrdado, potenciação

0     1
1     4
2     9
3    16
Name: col1, dtype: int64

In [240]:
del df['col2'] #deleta coluna 2

In [241]:
df

   col1 col3
0     1  abc
1     2  def
2     3  ghi
3     4  xyz

In [242]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [135]:
df.sort_values(by='col2', inplace = True) #ordena os dados pela coluna 2

In [248]:
df #voltou a pos. original

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [249]:
df.isnull #nao tem nulo, todos falsos

<bound method DataFrame.isnull of    col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi>

In [252]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [253]:
df['col1'].fillna(value=df['col1'].mean())

0    1.0
1    2.0
2    3.0
3    2.0
Name: col1, dtype: float64

In [254]:
df

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [136]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [137]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [138]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C']) #cria tabela dinamica usando D como valor

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

Entrada e saída de dados

In [139]:
df = pd.read_csv('exemplo.txt', sep=',') #le o arq separando por virgula

In [15]:
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [140]:
df = df + 1 #soma 1 em todos os valores num
df

    a   b   c   d
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [141]:
df.to_csv('exemplo.csv', sep=';', decimal=',')

In [142]:
df = pd.read_excel('Exemplo_Excel.xlsx', sheet_name='Sheet1')

In [143]:
df

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [144]:
df.to_excel('exemplo.xlsx', sheet_name='Sheet1') #salva o df em excel

In [145]:
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html') #le tabelas html web

In [146]:
type(df) #tipo do obj

list

In [147]:
len(df) #quantas tabelas encontradas no scrapping

1

In [148]:
df[0] #acessa primeira tabela encontrada

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
1,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
2,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
3,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
4,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
5,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
6,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
7,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
8,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
9,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
10,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
11,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
12,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
13,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
14,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
15,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
16,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
17,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
18,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
19,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
20,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
21,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
22,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
23,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
24,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525